[package]
name = "boat-cli"
version.workspace = true
edition.workspace = true
description = "Basic Opinionated Activity Tracker, a command line interface inspired by bartib"
repository.workspace = true
authors.workspace = true
readme = "../README.md"
license.workspace = true
keywords = ["cli", "time-tracking", "time-tracker", "productivity"]
categories = ["command-line-utilities", "filesystem"]
include = ["src/**", "Cargo.toml"]

[[bin]]
name = "boat"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
env_logger = { workspace = true }
log = { workspace = true }
clap-verbosity-flag = "3.0.4"
anyhow = { workspace = true }
directories = "6.0.0"
serde = { workspace = true }
toml = "1.0.7"
rusqlite = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
boat-lib = { workspace = true }
tabular = { version = "0.2.0", features = ["ansi-cell"] }
yansi = "1.0.1"
dialoguer = "0.12.0"
which = "8.0.2"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = { workspace = true }

[features]
default = []
bundled-sqlite = ["boat-lib/bundled-sqlite"]
